apiVersion: v1
kind: Service
metadata:
  name: {{ include "backend-nodejs.fullname" . }}
  labels:
    {{- include "backend-nodejs.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.nodePort }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
      nodePort: {{ .Values.service.nodePort }}
  {{- else }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  {{- end }}
  selector:
    {{- include "backend-nodejs.selectorLabels" . | nindent 4 }}
