apiVersion: v1
kind: Secret
metadata:
  name: {{ include "database-postgres.fullname" . }}
  labels:
    {{- include "database-postgres.labels" . | nindent 4 }}
type: Opaque
data:
  database-user: {{ .Values.database.user | b64enc | quote }}
  database-password: {{ .Values.database.password | b64enc | quote }}
  database-name: {{ .Values.database.name | b64enc | quote }}
  database-url: {{ printf "postgresql://%s:%s@%s:5432/%s" .Values.database.user .Values.database.password (include "database-postgres.fullname" .) .Values.database.name | b64enc | quote }}
