apiVersion: v1
kind: Service
metadata:
  name: {{ include "database-postgres.fullname" . }}
  labels:
    {{- include "database-postgres.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: postgresql
  selector:
    {{- include "database-postgres.selectorLabels" . | nindent 4 }}
