apiVersion: v2
name: frontend-react-native
description: Application frontend React native

version: 1.0.0

appVersion: "1.0.0"

keywords:
  - frontend
  - react native
  - application

home: https://github.com/Capgeminimum/capgeminimum-frontend.git
sources:
  - https://github.com/Capgeminimum/capgeminimum-frontend.git

dependencies:
  - name: backend
    version: 1.0.0
    repository: "https://github.com/Capgeminimum/capgeminimum-backend.git"

annotations:
 category: "Frontend"
 license: "MIT"

 